# Generated by Django 6.0.7 on 2026-08-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tier",
            field=models.CharField(
                choices=[("Low", "Low"), ("Mid", "Mid"), ("High", "High")],
                default="Mid",
                max_length=10,
            ),
        ),
    ]
