# Generated by Django 6.0.7 on 2026-08-29 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_tier"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPUSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("socket", models.CharField(max_length=50)),
                ("cores", models.PositiveIntegerField()),
                ("threads", models.PositiveIntegerField()),
                ("base_clock", models.CharField(max_length=20)),
                ("boost_clock", models.CharField(max_length=20)),
                ("tdp", models.CharField(max_length=20)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cpu_spec",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
