# Generated by Django 6.0.7 on 2026-08-29 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_cpuspecification"),
    ]

    operations = [
        migrations.CreateModel(
            name="GPUSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vram", models.CharField(max_length=50)),
                ("power_consumption", models.CharField(max_length=50)),
                ("interface", models.CharField(max_length=50)),
                ("length", models.CharField(max_length=50)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gpu_spec",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
