# Generated by Django 6.0.7 on 2026-08-29 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_gpuspecification"),
    ]

    operations = [
        migrations.CreateModel(
            name="RAMSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacity", models.CharField(max_length=50)),
                ("memory_type", models.CharField(max_length=50)),
                ("speed", models.CharField(max_length=50)),
                ("cas_latency", models.CharField(max_length=50)),
                ("voltage", models.CharField(max_length=50)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ram_spec",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
