# Generated by Django 6.0.7 on 2026-08-29 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_ramspecification"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotherboardSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("socket", models.CharField(max_length=50)),
                ("chipset", models.CharField(max_length=50)),
                ("form_factor", models.CharField(max_length=50)),
                ("ram_support", models.CharField(max_length=50)),
                ("max_ram", models.CharField(max_length=50)),
                ("m2_slots", models.PositiveIntegerField()),
                ("pcie", models.CharField(max_length=50)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="motherboard_spec",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
