# Generated by Django 6.0.7 on 2026-08-29 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_motherboardspecification"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacity", models.CharField(max_length=50)),
                ("storage_type", models.CharField(max_length=50)),
                ("interface", models.CharField(max_length=50)),
                ("read_speed", models.CharField(max_length=50)),
                ("write_speed", models.CharField(max_length=50)),
                ("form_factor", models.CharField(max_length=50)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_spec",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
