# Generated by Django 6.0.7 on 2026-08-29 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_storagespecification"),
    ]

    operations = [
        migrations.CreateModel(
            name="PSUSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wattage", models.CharField(max_length=20)),
                ("efficiency", models.CharField(max_length=50)),
                ("form_factor", models.CharField(max_length=50)),
                ("modular", models.CharField(max_length=50)),
                ("atx_version", models.CharField(max_length=50)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="psu_spec",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
