# Generated by Django 6.0.7 on 2026-08-29 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_psuspecification"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_factor", models.CharField(max_length=50)),
                ("motherboard_support", models.CharField(max_length=100)),
                ("gpu_length", models.CharField(max_length=50)),
                ("cpu_cooler_height", models.CharField(max_length=50)),
                ("radiator_support", models.CharField(max_length=100)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_spec",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
