# Generated by Django 6.0.7 on 2026-08-29 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_casespecification"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoolerSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cooler_type", models.CharField(max_length=50)),
                ("tdp_rating", models.CharField(max_length=50)),
                ("radiator_size", models.CharField(max_length=50)),
                ("fan_size", models.CharField(max_length=50)),
                ("height", models.CharField(max_length=50)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cooler_spec",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
