# Generated by Django 6.0.7 on 2026-09-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreBuiltPC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ai_ml", "AI / ML & Data Science"),
                            ("gaming", "Gaming & Streaming"),
                            ("entry", "Entry-Level"),
                            ("mid", "Mid-Level"),
                            ("creator", "Content Creation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("cpu", models.CharField(max_length=100)),
                ("gpu", models.CharField(max_length=100)),
                ("motherboard", models.CharField(max_length=100)),
                ("ram", models.CharField(max_length=100)),
                ("storage", models.CharField(max_length=100)),
                ("psu", models.CharField(max_length=100)),
                ("cooler", models.CharField(max_length=100)),
                ("cabinet", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="prebuilt_pcs/"),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
