# Generated by Django 6.0.7 on 2026-09-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_order_orderitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accessory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("monitor", "Monitors"),
                            ("keyboard", "Keyboards"),
                            ("mouse", "Mouse"),
                            ("gaming", "Gaming Accessories"),
                            ("audio", "Audio"),
                            ("desk", "Desk & Setup"),
                        ],
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="accessories/"),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
