# Generated by Django 6.0.7 on 2026-09-11 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_accessory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="cartitem_exactly_one_target",
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("user", "prebuilt_pc"), ("user", "product")},
        ),
        migrations.AddField(
            model_name="cartitem",
            name="accessory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="products.accessory",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="accessory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="products.accessory",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={
                ("user", "accessory"),
                ("user", "prebuilt_pc"),
                ("user", "product"),
            },
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("accessory__isnull", True),
                        ("prebuilt_pc__isnull", True),
                        ("product__isnull", False),
                    ),
                    models.Q(
                        ("accessory__isnull", True),
                        ("prebuilt_pc__isnull", False),
                        ("product__isnull", True),
                    ),
                    models.Q(
                        ("accessory__isnull", False),
                        ("prebuilt_pc__isnull", True),
                        ("product__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="cartitem_exactly_one_target",
            ),
        ),
    ]
