# Generated by Django 6.0.7 on 2026-09-11 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_remove_cartitem_cartitem_exactly_one_target_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accessory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="products.accessory",
                    ),
                ),
                (
                    "prebuilt_pc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="products.prebuiltpc",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("accessory__isnull", True),
                                ("prebuilt_pc__isnull", True),
                                ("product__isnull", False),
                            ),
                            models.Q(
                                ("accessory__isnull", True),
                                ("prebuilt_pc__isnull", False),
                                ("product__isnull", True),
                            ),
                            models.Q(
                                ("accessory__isnull", False),
                                ("prebuilt_pc__isnull", True),
                                ("product__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="wishlistitem_exactly_one_target",
                    )
                ],
                "unique_together": {
                    ("user", "accessory"),
                    ("user", "prebuilt_pc"),
                    ("user", "product"),
                },
            },
        ),
    ]
